from dotenv import load_dotenv
import os

load_dotenv()
OPENSEARCH_INDEX_NAME = os.getenv("OPENSEARCH_INDEX_NAME")
OPENSEARCH_CLUSTER_ENDPOINT = os.getenv("OPENSEARCH_CLUSTER_ENDPOINT")
OPENSEARCH_HOST_PORT = os.getenv("OPENSEARCH_HOST_PORT")
OPENSEARCH_USERNAME = os.getenv("OPENSEARCH_USERNAME")
OPENSEARCH_PASSWORD = os.getenv("OPENSEARCH_PASSWORD")

__all__ = [
    "OPENSEARCH_INDEX_NAME",
    "OPENSEARCH_CLUSTER_ENDPOINT",
    "OPENSEARCH_HOST_PORT",
    "OPENSEARCH_USERNAME",
    "OPENSEARCH_PASSWORD"
]
